sources = [
    {
        "key": "greenhouse:gitlab",
        "handler": "greenhouse",
        "board": "gitlab",
        "company": "GitLab",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "greenhouse:cloudflare",
        "handler": "greenhouse",
        "board": "cloudflare",
        "company": "Cloudflare",
        "region": "global",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "greenhouse:elastic",
        "handler": "greenhouse",
        "board": "elastic",
        "company": "Elastic",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "greenhouse:datadog",
        "handler": "greenhouse",
        "board": "datadog",
        "company": "Datadog",
        "region": "us-eu",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "greenhouse:dropbox",
        "handler": "greenhouse",
        "board": "dropbox",
        "company": "Dropbox",
        "region": "us",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "greenhouse:twilio",
        "handler": "greenhouse",
        "board": "twilio",
        "company": "Twilio",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "greenhouse:stripe",
        "handler": "greenhouse",
        "board": "stripe",
        "company": "Stripe",
        "region": "us-eu",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "greenhouse:vercel",
        "handler": "greenhouse",
        "board": "vercel",
        "company": "Vercel",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "greenhouse:duckduckgo",
        "handler": "greenhouse",
        "board": "duckduckgo",
        "company": "DuckDuckGo",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 720,
    },
    {
        "key": "greenhouse:grafanalabs",
        "handler": "greenhouse",
        "board": "grafanalabs",
        "company": "Grafana Labs",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "lever:plaid",
        "handler": "lever",
        "org": "plaid",
        "company": "Plaid",
        "region": "us-eu",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "lever:palantir",
        "handler": "lever",
        "org": "palantir",
        "company": "Palantir",
        "region": "us-eu",
        "active": True,
        "poll_minutes": 720,
    },
    {
        "key": "lever:netlify",
        "handler": "lever",
        "org": "netlify",
        "company": "Netlify",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 720,
    },
    {
        "key": "ashby:linear",
        "handler": "ashby",
        "org": "linear",
        "company": "Linear",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "ashby:ramp",
        "handler": "ashby",
        "org": "ramp",
        "company": "Ramp",
        "region": "us",
        "active": True,
        "poll_minutes": 720,
    },
    {
        "key": "ashby:posthog",
        "handler": "ashby",
        "org": "posthog",
        "company": "PostHog",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "ashby:supabase",
        "handler": "ashby",
        "org": "supabase",
        "company": "Supabase",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 360,
    },
    {
        "key": "ashby:deel",
        "handler": "ashby",
        "org": "deel",
        "company": "Deel",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 720,
    },
    {
        "key": "linkedin:guest",
        "handler": "linkedin",
        "keywords": "software engineer",
        "location": "Remote",
        "region": "remote-global",
        "active": True,
        "poll_minutes": 720,
    },
]
